name: Study task
description: 주차별 학습 과제 등록
title: "[WeekN] 이름 - 과제 제목"

body:
  - type: input
    id: name
    attributes:
      label: 이름
      placeholder: 홍길동
    validations:
      required: true

  - type: dropdown
    id: team
    attributes:
      label: 팀
      options:
        - 인지
        - 보행
    validations:
      required: true

  - type: dropdown
    id: week
    attributes:
      label: 주차
      options:
        - Week1
        - Week2
        - Week3
    validations:
      required: true

  - type: textarea
    id: goal
    attributes:
      label: 학습 내용
      description: 이번 과제에서 구현한 내용 및 배운 점 (자유롭게 작성)
    validations:
      required: true

  - type: textarea
    id: references
    attributes:
      label: 참고 자료
      description: 공부하는데 도움이 된 참고자료
